version: '2'
services:
    paypalsampleapp-mysql:
        image: mysql:5.7.20
        volumes:
            - ~/volumes/jhipster/PaypalSampleApp/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=qualitycodebase@2019
            - MYSQL_DATABASE=paypalsampleapp
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
